### ISSUE TITLE
Ireal Pro playlist not recognized as such

### ISSUE THREAD

**Issue by LucasPa** [infojunkie/chirp#1]
Hello,

Thanks for providing this nice tool. I tried it on the playlists found on [this post](https://www.irealb.com/forums/showthread.php?10591-Dixieland-Trad-Playlists). It works successfully on the second playlist "Dixieland Tunes 2". However for the first and third playlists "Dixieland Tunes 1" and "Dixieland Tunes 3" the error "This URI is not recognized as an iReal Pro playlist." is raised after converting successfully 19 and 5 songs respectively.

Do you have any clue what is wrong here?

Best,

Lucas

**Comment by infojunkie** [comment]
Hi, thanks for reporting. I'll take a look when I get some time over the weekend. In the meantime, if you have some JavaScript coding experience, you can open up the browser console log and find the error that occurs. Most likely it's the iReal Pro parser that received a tune it can't handle.

**Comment by LucasPa** [comment]
I'm sorry that goes beyond my skills. I have no experience in JavaScript coding. I had to ask Google to show me how to open the browser console log. But the latter did not really helped me as I did not know what to look at.

**Comment by infojunkie** [comment]
Thanks, don't worry about it. I'll get back to you soon.

**Comment by infojunkie** [comment]
I fixed the app to continue transforming songs even if it encounters errors. This should keep you going for now, but I still need to figure out why it fails to transform those 5 or 6 songs.

**Comment by LucasPa** [comment]
Thanks, I confirm that it is now possible to work on three playlists of the above given link.
