### ISSUE TITLE
Possible Use of Song Name in Track Name

### ISSUE THREAD

**Issue by SJ02** [infojunkie/chirp#4]
Hi.   A multi-selection of ChiRP -written MIDI files, when dragged into Ableton Live as clips, ends up there with all the clips having the same name:  "Chord-Custom".   

If possible and reasonable in all other senses, I think it would be helpful if the files were written in a way such that when dragged into Ableton Live as clips then the clips each are named for the individual song rather than "Chord-Custom".   

Thanks for considering this.

**Comment by infojunkie** [comment]
Thanks for the suggestion. Sounds reasonable - I just need to think how to make this customization work in the general case. I will report back here with updates.

**Comment by infojunkie** [comment]
I've made a change to ChiRP and its backend [`musicxml-midi`](https://github.com/infojunkie/musicxml-midi) to include the input filename in the track name. For example:
- "Metadata track for anything-goes.musicxml"
- "Chord track for anything-goes.musicxml"
etc.

Hope this helps!
